**Problem 1**

Import Numpy as np

In [1]:
import numpy as np

**Problem 2**

Create a 1D array of numbers from 0 to 9.

In [2]:
a = np.array([0,1,2,3,4,5,6,7,8,9])

**Problem 3**

Create a 3×3 numpy array of all True’s.

In [3]:
array1 = np.array([[["True","True","True"],["True","True","True"],["True","True","True"]]])
print(array1)

[[['True' 'True' 'True']
  ['True' 'True' 'True']
  ['True' 'True' 'True']]]


**Problem 4**

Extract all odd numbers from arr.

In [4]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(np.extract(arr % 2 == 1, arr))

[1 3 5 7 9]


**Problem 5**

Replace all odd numbers in arr with -1.

In [5]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(np.where(arr % 2 == 1, -1, arr))

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


**Problem 6**

Convert a 1D array to a 2D array with 2 rows.

In [6]:
arr = np.arange(10)
print(arr)


[0 1 2 3 4 5 6 7 8 9]


In [7]:
print(arr.reshape(2, -1))

[[0 1 2 3 4]
 [5 6 7 8 9]]


**Problem 7** 

Stack arrays a and b vertically.

In [8]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(a,b)

[[0 1 2 3 4]
 [5 6 7 8 9]] [[1 1 1 1 1]
 [1 1 1 1 1]]


**Problem 8**

Stack the arrays a and b horizontally.

In [9]:
c = np.hstack((a,b))
print(c)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


**Problem 9**

Get the common items between a and b.

In [10]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

print(arr[a==b])

[1 3 5 7]


**Problem 10**

From array a remove all items present in array b

In [11]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
c=np.delete(a,[4],None)
#print(len(b), len(a))
print(c)


[1 2 3 4]


**Problem 11**

Get the positions where elements of a and b match

In [12]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

#option1
# np.where(np.in1d(a, b))[0]
#option 2
print(np.where(np.isin(a, b)))

(array([1, 3, 5, 7], dtype=int64),)


**Problem 12** 

Get all items between 5 and 10 from a.

In [13]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

#option 1
#np.sort(a)[3:5]

print(a[np.logical_and(a>=5, a<=10)])


[ 6  9 10]


**Problem 13**

Swap columns 1 and 2 in the array arr.

In [14]:
print("before Swap")
print(arr)
arr = np.arange(9).reshape(3,3)

print("after swap")
print(arr)
arr[:,[1, 0]] = arr[:,[0, 1]]

#print(arr.swapaxes(0,1))


before Swap
[0 1 2 3 4 5 6 7 8 9]
after swap
[[0 1 2]
 [3 4 5]
 [6 7 8]]


**Problem 14**

Swap rows 1 and 2 in the array arr.

In [15]:
arr = np.arange(9).reshape(3,3)
print("before swap")
print(arr)
arr[[1,0]] = arr [[0,1]]
print("After Swap")
print(arr)

before swap
[[0 1 2]
 [3 4 5]
 [6 7 8]]
After Swap
[[3 4 5]
 [0 1 2]
 [6 7 8]]


**Problem 15**

Reverse the rows of a 2D array arr.

In [16]:
arr = np.arange(9).reshape(3,3)
print("Before", end="\n")
print(arr, end="\n")
new_arr = np.sort(arr)[::-1]
print("After", end="\n")
print(new_arr)


Before
[[0 1 2]
 [3 4 5]
 [6 7 8]]
After
[[6 7 8]
 [3 4 5]
 [0 1 2]]


**Problem 16**

Reverse the columns of a 2D array arr.

In [17]:
arr = np.arange(9).reshape(3,3)
print(arr)
print(np.flip(arr,0))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[6 7 8]
 [3 4 5]
 [0 1 2]]


**Problem 17**

Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10

In [19]:
import random

rand_arr = np.random.rand(5,3) * 5 + 5
print(rand_arr.round(3))

[[6.181 6.809 9.832]
 [5.506 9.507 8.573]
 [9.534 5.128 5.788]
 [7.076 7.173 6.963]
 [6.174 5.847 9.153]]


**Problem 18**

Print or show only 3 decimal places of the numpy array rand_arr.

In [20]:
np.round(rand_arr,3)

array([[6.181, 6.809, 9.832],
       [5.506, 9.507, 8.573],
       [9.534, 5.128, 5.788],
       [7.076, 7.173, 6.963],
       [6.174, 5.847, 9.153]])